name: Run tests

on:
  push:
    branches-ignore: [ release ]
  pull_request:
    branches: [ main release ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Restore gems cache
        id: cache-gems-restore
        uses: actions/cache/restore@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('Gemfile') }}-${{ hashFiles('spec/dummy/Gemfile') }}-${{ hashFiles('yes-command-api.gemspec') }}
      - name: Install gems
        run: |
          mkdir -p vendor/bundle
          bundle config set --local path vendor/bundle
          bundle install
        env:
          BUNDLE_GEM__FURY__IO: ${{secrets.GEM_FURY_TOKEN}}
      - name: Save gems cache
        id: cache-gems-save
        uses: actions/cache/save@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('Gemfile') }}-${{ hashFiles('spec/dummy/Gemfile') }}-${{ hashFiles('yes-command-api.gemspec') }}
      - name: Run Test Dependencies[Postgres, Redis]
        run: docker compose up --detach
      - name: Run tests
        run: |
          sleep 10
          ./bin/setup_db
          TEST_COVERAGE=true bundle exec rspec
        env:
          BUNDLE_GEM__FURY__IO: ${{secrets.GEM_FURY_TOKEN}}
