plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'sig/**/*'
    - 'db/**/*'
    - '**/db/**/*'

# --- Metrics ---

Metrics/AbcSize:
  Max: 60

Metrics/ClassLength:
  CountComments: false
  Max: 200
  CountAsOne: []

Metrics/MethodLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 18

Metrics/PerceivedComplexity:
  Max: 18

Metrics/ParameterLists:
  Max: 8

Metrics/BlockLength:
  Max: 60
  Exclude:
    - '**/spec/**/*'
    - '**/factories/**/*'
    - '**/config/routes.rb'
    - '**/tasks/eventstore.rake'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - '**/spec/**/*'
    - '**/factories/**/*'
    - '**/config/routes.rb'

# --- Layout ---

Layout/LineLength:
  Max: 180
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - '**/spec/**/*'

Layout/DotPosition:
  EnforcedStyle: trailing

# --- Lint ---

Lint/DuplicateBranch:
  Enabled: true
  IgnoreLiteralBranches: true

Lint/NumberConversion:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/ShadowedArgument:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/ReturnInVoidContext:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/InterpolationCheck:
  Enabled: false

Lint/NonAtomicFileOperation:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

# --- Style ---

Style/Documentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/EndlessMethod:
  EnforcedStyle: disallow

Style/OpenStructUse:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - '**/spec/**/*'

Style/ItAssignment:
  Enabled: false


Lint/DuplicateMethods:
  Exclude:
    - '**/spec/**/*'

# --- Naming ---

Naming/VariableNumber:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

# --- Bundler ---

Bundler/GemComment:
  Enabled: false

# --- Rails ---

Rails/SkipsModelValidations:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false
