version: "3.5"

services:
  redis:
    image: redis:7
    ports:
      - 6479:6379
  postgres:
    image: postgres:16
    ports:
      - 5532:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - "./db/postgresql/data:/var/lib/postgresql/data"
