# frozen_string_literal: true

require File.expand_path('config/application', __dir__)
require 'active_record'
require 'active_record/tasks/database_tasks'

include ActiveRecord::Tasks

DatabaseTasks.env = ENV.fetch('RAILS_ENV', 'test')
DatabaseTasks.db_dir = File.expand_path('db', __dir__)
DatabaseTasks.database_configuration = YAML.load_file(File.expand_path('config/database.yml', __dir__), aliases: true)
DatabaseTasks.migrations_paths = [File.expand_path('db/migrate', __dir__)]

task :environment do
  ActiveRecord::Base.configurations = DatabaseTasks.database_configuration
  ActiveRecord::Base.establish_connection(DatabaseTasks.env.to_sym)
end

load 'active_record/railties/databases.rake'
