version: "3.5"

services:
  redis:
    image: redis:6.2.7-alpine
    ports:
      - 6479:6379
  postgres:
    image: postgres:16
    ports:
      - 5532:5432
    environment:
      - POSTGRES_PASSWORD=postgres
