# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.6'

# Specify your gem's dependencies in yes.gemspec
gemspec

gem 'rake', '~> 13.0'

source 'https://gem.fury.io/yousty-ag/' do
  gem 'yousty-eventsourcing', '~> 12'
end

group :development, :test do
  gem 'jwt_token_auth_client_rails', '~> 3.3'
  gem 'yousty-command-api', path: '../yousty-command-api'
  gem 'yousty-read-api', path: '../yousty-read-api'

  gem 'database_cleaner-active_record'
  gem 'generator_spec'
  gem 'rails', '~> 7.2'
  gem 'rspec', '~> 3.0'
  gem 'rspec-rails', '~> 7.1'
  gem 'rubocop', '~> 1.21'
end
