# frozen_string_literal: true

module Dummy
  module Activity
    module Commands
      module DoSomething
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end
      end

      module DoSomethingElse
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end
      end

      module DoSomethingImpossible
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end
      end

      module DoSomethingMoreImpossible
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            raise CommandNotAuthorized, 'You cannot do this'
          end
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            raise CommandInvalid
          end
        end
      end

      module DoAnotherImpossible
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end
      end

      module DoSomethingLocalized
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          attribute :locale, Yes::Core::Types::String
          alias aggregate_id id
        end
      end

      module DoSomethingUncommon
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            raise CommandInvalid, 'This is not valid'
          end
        end
      end

      module DoSomethingAuthorized
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end
      end

      module DoSomethingUnauthorized
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            raise CommandNotAuthorized, "Don't do this"
          end
        end
      end

      module DoSomethingInvalid
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            raise CommandInvalid.new('Command is invalid', extra: { foo: :bar })
          end
        end
      end
    end

    # Aggregate-DSL CommandGroup dummy. Generated by the `command_group`
    # macro in production; here it's hand-rolled (parallel to the
    # hand-rolled regular-command dummies above) so request specs can
    # exercise the new dispatch path without setting up a real
    # Yes::Core::Aggregate subclass. Uses sub-commands that already have
    # an Authorizer defined so BatchAuthorizer doesn't reject them.
    module CommandGroups
      module DoTwoThings
        class Command < Yes::Core::Commands::CommandGroup
          self.context = 'Dummy'
          self.aggregate = 'Activity'
          self.group_name = :do_two_things
          self.sub_command_names = %i[do_something_else do_something_authorized]
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            true
          end
        end
      end
    end
  end

  module Actions
    module Commands
      module DoSomething
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            true
          end
        end
      end

      module DoSomethingElse
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end
      end

      module DoSomethingUnauthorized
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            raise CommandNotAuthorized, "V2 Don't do this"
          end
        end
      end

      module DoSomethingInvalid
        class Command < Yes::Core::Command
          attribute :what, Yes::Core::Types::String
          attribute :id, Yes::Core::Types::UUID
          alias aggregate_id id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            raise CommandInvalid, 'V2 Command is invalid'
          end
        end
      end
    end
  end

  module V23
    module Activity
      class DoSomething < Yes::Core::Command
        attribute :what, Yes::Core::Types::String
        attribute :id, Yes::Core::Types::UUID
        alias aggregate_id id
      end
    end
  end

  module User
    module Commands
      module ChangeName
        class Command < Yes::Core::Command
          attribute :first_name, Yes::Core::Types::String
          attribute :last_name, Yes::Core::Types::String
          attribute :user_id, Yes::Core::Types::UUID
          alias aggregate_id user_id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            true
          end
        end
      end
    end
  end

  module Company
    module Commands
      module ChangeName
        class Command < Yes::Core::Command
          attribute :name, Yes::Core::Types::String
          attribute :company_id, Yes::Core::Types::UUID
          alias aggregate_id company_id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            true
          end
        end
      end

      module ChangeDescription
        class Command < Yes::Core::Command
          attribute :description, Yes::Core::Types::String
          attribute :company_id, Yes::Core::Types::UUID
          alias aggregate_id company_id
        end

        class Authorizer < Yes::Core::Authorization::CommandAuthorizer
          def self.call(_command, _auth_data)
            true
          end
        end

        class Validator < Yes::Core::Commands::Validator
          def self.call(_command)
            true
          end
        end
      end

      module DoSomethingCompounded
        class Command < Yes::Core::Commands::Group
          command 'ChangeName'
          command 'ChangeDescription'
          command 'ChangeName', subject: 'User'
        end
      end
    end
  end
end

# Register the hand-rolled sub-commands in the configuration registry so
# `Yes::Core::Commands::CommandGroup#sub_command_classes` can resolve them.
# Real aggregate-DSL commands are registered automatically by
# `ClassResolvers::Command::Command#generate_class`; the dummies bypass that
# pipeline, so we do it manually here.
Yes::Core.configuration.register_command_class(
  'Dummy', 'Activity', :do_something_else,
  Dummy::Activity::Commands::DoSomethingElse::Command
)
Yes::Core.configuration.register_command_class(
  'Dummy', 'Activity', :do_something_authorized,
  Dummy::Activity::Commands::DoSomethingAuthorized::Command
)
