# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in yes-command-api.gemspec.
gemspec

instance_eval(File.read(File.expand_path('spec/dummy/Gemfile', __dir__)))

gem 'message_bus', git: 'https://github.com/yousty/message_bus.git'
gem 'yes-core', path: '../yes-core'

group :development, :test do
  gem 'dotenv-rails', '~> 2.8'
  gem 'jwt', '~> 2.7'
  gem 'opentelemetry-sdk'
  gem 'rake', '~> 13.0'
  gem 'rbnacl'
  gem 'redis', '~> 5.0'
  gem 'rspec', '~> 3.0'
  gem 'rspec-rails', '~> 6.0.2'
  gem 'simplecov', '~> 0.21'
  gem 'simplecov-formatter-badge', '~> 0.1'
end
