# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in yousty_dev_tools.gemspec
gemspec

source 'https://gem.fury.io/yousty-ag/' do
  gem 'jwt_token_auth_client_rails', '~> 3.3'
  gem 'yousty_dev_tools', '~> 0.1'
  gem 'yousty-eventsourcing', '~> 15.0.1'
  gem 'yousty-api', '~> 1.5'
end

instance_eval(File.read(File.expand_path('dummy_app/Gemfile', __dir__)))
