# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in yes-read-api.gemspec
gemspec

gem 'yes-core', path: '../yes-core'

group :development, :test do
  gem 'dotenv-rails', '~> 2.8'
  gem 'factory_bot', '~> 6.0'
  gem 'jwt', '~> 2.7'
  gem 'opentelemetry-sdk'
  gem 'rake', '~> 13.0'
  gem 'rbnacl'
  gem 'rspec', '~> 3.0'
  gem 'rspec-rails', '~> 6.0.2'
end

instance_eval(File.read(File.expand_path('spec/dummy/Gemfile', __dir__)))
