# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.5'

gemspec

gem 'yes-core', path: '../yes-core'

group :development, :test do
  gem 'factory_bot', '~> 6.0'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.0'
  gem 'rspec-rails', '~> 7.1'
  gem 'sqlite3'
end
