name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: |
          echo "GEM_FURY_TOKEN Secret:"
          echo ${{ secrets.GEM_FURY_TOKEN }}
          bundle install
          bundle exec rspec
        env:
          BUNDLE_GEM__FURY__IO: ${{secrets.GEM_FURY_TOKEN}}
