name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Run Test Dependencies (Postgres, Redis)
        run: docker compose up --detach
      - name: Run tests
        run: |
          bundle install
          sleep 10
          ./bin/setup_db
          bundle exec rspec yes-core/spec
        env:
          BUNDLE_GEM__FURY__IO: ${{secrets.GEM_FURY_TOKEN}}
